### ISSUE TITLE
SandboxRunner class should have an option for LedgerId while startup

### ISSUE THREAD

**Issue by ThejaswaniBheemanatham** [digital-asset/lib-daml-jvm-test#20]
Current implementation doesn't have option for ledger Id during sandbox runner initialisation.
This option would help to write some tests around "Unknown Ledger Id" exceptions when sandbox restarts.

**Comment by tamaskalcza-da** [comment]
@ThejaswaniBheemanatham thank you for creating this issue. I am happy to inform you that `0.1.15` version of the library is out, which has support for configuring custom ledger id.

Example:
```java
Sandbox.builder()
    .dar(DAR_PATH)
    .ledgerId("MyCustomLedger")
    .build();
```

You can also get the ledger id in a more straightforward way, directly from the `Sandbox` instance.
```java
Sandbox sandbox = ...;
sandbox.getLedgerId();
```

You can also check the integration test for a full example: https://github.com/digital-asset/lib-daml-jvm-test/blob/master/src/test/java/com/digitalasset/testing/junit4/SandboxIT.java
